### ISSUE TITLE
Resolve puppeteer global dependency

### ISSUE THREAD

**Issue by jmckible** [techvalidate/portrait#16]
Right now you are required to install node, npm, puppeteer, and minimist globally.

We should either put this into the bin/setup script OR reconfigure to use the version installed by yarn.

**Comment by tjdo** [comment]
I think this is a non-issue. Puppeteer and miniminst are locally installed and used locally (at least in my environments and testing). Node and npm should be global, as Node is an app server and npm is it's package manager, much like Ruby and gem
