### ISSUE TITLE
Please remove my Access. Thanks :-)

### ISSUE THREAD

**Issue by ckizer** [techvalidate/portrait#58]
I'm still getting notifications for this. Please remove my user ckizer from the Techvalidate repos.
Better security I think.

Cheers :-)

**Comment by andrewckennedy** [comment]
Hey Court, this is a public repo so I think you have to unwatch it to stop getting notifications. 

Hope all is well with you!

**Comment by ckizer** [comment]
Well that just makes too much sense :-) Will Do. I was worried I still had access to the private repo. Cheers Andrew!

**Comment by mmlindeboom** [comment]
👋😁
